# Generated by Django 3.2.12 on 2022-04-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userwithbirthday_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwithbirthday',
            options={'verbose_name': 'Расширенный пользователь', 'verbose_name_plural': 'Расширенные пользователи'},
        ),
    ]
