# Generated by Django 3.2.12 on 2022-04-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userwithbirthday_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithbirthday',
            name='email',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='email'),
        ),
    ]
