# Generated by Django 3.2.12 on 2022-04-20 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_rename_email_userwithbirthday_authentication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithbirthday',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
