# Generated by Django 3.2.12 on 2022-03-22 15:10

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='видимость сущности')),
                ('slug', models.SlugField(max_length=200, verbose_name='подкаталог сущности')),
                ('weight', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='видимость сущности')),
                ('slug', models.SlugField(max_length=200, verbose_name='подкаталог сущности')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='видимость сущности')),
                ('name', models.CharField(max_length=150, verbose_name='имя товара')),
                ('text', models.TextField(validators=[catalog.validators.text_validator], verbose_name='описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='catalog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='catalog_items', to='catalog.Tag', verbose_name='тэги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('weight__lt', 32767)), name='weight_lt_32767'),
        ),
    ]
