# Generated by Django 3.2.12 on 2022-04-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220425_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='data',
        ),
        migrations.AddField(
            model_name='item',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='иконка товара'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображения товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'галлерея',
            },
        ),
    ]
